accounts/urls.py
from django.urls import path

from accounts.views.create_view import create_form, receive_form
from accounts.views.jwt_token import make_tokens_for_user
from accounts.views.login_view import (login_form, logout_user, painel_cliente,
                                       verify_user)
from accounts.views.recover_view import proccess_recovery, recover_view

app_name='accounts'

urlpatterns = [
    path('', login_form, name='login'),
    path('create/client/', receive_form, name='create_client'),
    path('recover/pass/', recover_view, name='recovery'),
    path('change/pass/', proccess_recovery, name='change_pass'),
    path('client/pair', make_tokens_for_user, name='make_tokens'),
    path('client/', painel_cliente, name='client'),
    path('create/', create_form, name='create'),
    path('login/', verify_user, name='verify_login'),
    path('logout/', logout_user, name='logout'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.api_account import api_auth
from persons.api import api

urlpatterns = [
    path('manutencao/', admin.site.urls),
    path('', include('persons.urls'), name='inicio'),
    path('account/api/v1/', api_auth.urls),
    path('account/', include('accounts.urls'), name='login'),
    path('api/v1/', api.urls),
]

handler404 = "persons.views.handler404"

persons/urls.py
from django.urls import path

from .views import initial

app_name='persons'

urlpatterns = [
    path('', initial, name='initial'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class ClientAccountToken(models.Model):
    
    class Meta:
        verbose_name='Cliente Token'
        verbose_name_plural='Clientes Tokens'
    
    username = models.ForeignKey(User, on_delete=models.CASCADE)    
    refresh_token = models.CharField(blank=True, max_length=300, verbose_name='Refresh Token')
    access_token = models.CharField(blank=True, max_length=300, verbose_name='Access Token')
    date = models.DateField(null=True, verbose_name='Criado em')
    
    def __str__(self) -> str:
        return f'{self.username}, {self.refresh_token}, {self.access_token}, {self.date}'
        

accounts/forms/form_create.py
import re
from collections import defaultdict

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

WIDGET_CLASS = 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5'

def strongPasword(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')
    
    if not regex.match(password):
        raise ValidationError(('Digite pelo menos 8 caracteres entre letras maiúsculas e minúsculas e números.'),
                              code='Inválido')
    

class RegisterForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.listerrors= defaultdict(list)
    
    
    password = forms.CharField(
        required=True,
        widget= forms.PasswordInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'Digite uma senha forte',
                'minlength':8,
                'type':'password',
            }
        ),
        validators=[strongPasword],
        label='Senha',
    )
    
    password_confirm = forms.CharField(
        required=True,
        widget= forms.PasswordInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'Repita a senha digitada',
                'minlength':8,    
                'type':'password',
            }
        ),
        validators=[strongPasword],
        label='Confirmar senha',
    )
    
    class Meta:
        model= User
        
        fields= [
            'username',
            'first_name',
            'email',
            'password',
        ]
       

            
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class':WIDGET_CLASS,
                    'placeholder':'Crie seu nome de usuário',
                    'minlength':3,
                    'required':True,
                }
            ),
            
            'first_name': forms.TextInput(
                attrs={
                    'class':WIDGET_CLASS,
                    'placeholder':'Seu nome',
                    'minlength':3,
                    'required':True,
                }
            ),
           
            'email': forms.EmailInput(
                attrs={
                    'class':WIDGET_CLASS,
                    'placeholder':'Seu email',
                    'required':True,
                }
            )
        }


# VALIDAÇÃO DE CAMPOS

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        
        clean_data= self.cleaned_data
        
        newuser= clean_data.get('username')
        name= clean_data.get('first_name')
        email= clean_data.get('email')
        password= clean_data.get('password')
        password_confirm= clean_data.get('password_confirm')
        
        user_exists= User.objects.filter(username=str(newuser).lower()).exists()
        if user_exists:
            self.listerrors['username'].append('Usuário já está cadastrado!')
        elif len(newuser) < 3:
            self.listerrors['username'].append('Nomes de usuário devem ter 3 ou mais caracteres')
        
        if len(name) < 3:
            self.listerrors['name'].append('Primeiro nome deve ter 3 ou mais caracteres')

        email_exists= User.objects.filter(email=str(email).lower()).exists()
        if email_exists:
            self.listerrors['email'].append('E-mail já está cadastrado!')
        
        if password != password_confirm:
            self.listerrors['password'].append('Senhas digitadas são diferentes!')
            self.listerrors['password_confirm'].append('Senhas digitadas são diferentes!')

        if self.listerrors:
            raise ValidationError(self.listerrors)
        
        return super_clean
        

accounts/forms/form_recover.py
from collections import defaultdict

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

WIDGET_CLASS = 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5'

class RecoverForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.listerrors= defaultdict(list)
    
    
    password = forms.CharField(
        required=True,
        widget= forms.PasswordInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'Digite uma senha forte',
                'minlength':8,
                'type':'password',
            }
        ),
        validators=[],
        label='Senha',
    )
    
    password_confirm = forms.CharField(
        required=True,
        widget= forms.PasswordInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'Repita a senha digitada',
                'minlength':8,    
                'type':'password',
            }
        ),
        validators=[],
        label='Confirmar senha',
    )
    
    class Meta:
        model= User
        
        fields= [
            'email',
            'password',
        ]

            
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class':WIDGET_CLASS,
                    'placeholder':'Seu email de cadastro',
                    'required':True,
                }
            )
        }


# VALIDAÇÃO DE CAMPOS

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        
        clean_data= self.cleaned_data
        
        email= clean_data.get('email')
        password= clean_data.get('password')
        password_confirm= clean_data.get('password_confirm')
        

        email_exists= User.objects.filter(email=email).exists()
        if not email_exists:
            self.listerrors['email'].append('E-mail não existe no cadastrado!')
        
        if password != password_confirm:
            self.listerrors['password'].append('Senhas digitadas são diferentes!')
            self.listerrors['password_confirm'].append('Senhas digitadas são diferentes!')

        if self.listerrors:
            raise ValidationError(self.listerrors)
        
        return super_clean
        

accounts/forms/login_form.py
from django import forms

WIDGET_CLASS = 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5'

class LoginForm(forms.Form):
       
    username= forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'Usuário',
            }
        )
    )
    
    password= forms.CharField(
        required=True,
        widget= forms.PasswordInput(
            attrs={
                'class':WIDGET_CLASS,
                'placeholder':'**********',
            }
        )
    )
    

accounts/views/create_view.py
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.shortcuts import redirect, render

from accounts.forms.form_create import RegisterForm


def create_form(request):
    register_data = request.session.get('register_form_data', None)
    
    create_user_form = RegisterForm(register_data)
    return render(request, 'accounts/create.html',{'create_user_form':create_user_form})

def receive_form(request):
    if not request.POST:
        del(request.session['register_form_data'])
        return redirect('accounts:create')
    
    POST_DATA = request.POST
    request.session['register_form_data'] = POST_DATA
    form = RegisterForm(POST_DATA)
    
    if form.is_valid():
        data = form.save(commit=False)
        data.username = data.username.lower()
        data.first_name = data.first_name.capitalize()
        data.email = data.email.lower()
        data.password = make_password(data.password)
        
        form.save(commit=True) #commit=False não salva dados
        del(request.session['register_form_data'])
        messages.success(request, 'Conta criada com sucesso!')
    
    return redirect('accounts:create')

accounts/views/jwt_token.py
from datetime import date

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from ninja_jwt.tokens import RefreshToken

from accounts.models import ClientAccountToken


@login_required(login_url='accounts:login', redirect_field_name='next')
def make_tokens_for_user(request):
    
    # Vai tentar atualizar a chave de API se o suário já possuir uma chave anterior vencida.
    try:
        refresh = RefreshToken.for_user(request.user)
        
        client = ClientAccountToken.objects.get(username=request.user)
        client.refresh_token = refresh
        client.access_token = refresh.access_token
        client.date = date.today()
        client.save()
        
        messages.success(request, 'Chave atualizada com sucesso!')
        return redirect('accounts:client')
    
    # Caso contrário se for o primeiro acesso, vai criar um par de chaves de acesso a API
    except ClientAccountToken.DoesNotExist:
        newToken = RefreshToken.for_user(request.user)
        newclient = ClientAccountToken()
        newclient.username = request.user
        newclient.refresh_token = newToken
        newclient.access_token = newToken.access_token
        newclient.date = date.today()
        newclient.save()

        messages.success(request, 'Token criado com sucesso!')
        return redirect('accounts:client')

    
    

accounts/views/login_view.py
from datetime import date

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from accounts.forms.login_form import LoginForm
from accounts.models import ClientAccountToken


def login_form(request):
    user_data_form = LoginForm()
    return render(request, 'accounts/userlogin.html',{'user_data_form':user_data_form})


def verify_user(request):
    if not request.POST:
        return redirect('accounts:login')
    
    login_data = LoginForm(request.POST)

    if login_data.is_valid():
        authenticated_user= authenticate(
            username=login_data.cleaned_data.get('username',''),
            password=login_data.cleaned_data.get('password',''),
        )

        if authenticated_user is not None:
            login(request, authenticated_user)
        else:
            messages.error(request, 'Dados incorretos!')
    else:
        messages.error(request, 'Dados incorretos!')
    return redirect('accounts:login')


@login_required(login_url='accounts:login', redirect_field_name='next')
def logout_user(request):
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login', redirect_field_name='next')
def painel_cliente(request):
    # Se usuário já tiver Token ativo ou não serão exibidos os dados.
    try:
        user_token = ClientAccountToken.objects.filter(username=request.user).first()
       
        if user_token:
            expirado=False
            validade = date.today()
            expirado = True if validade != user_token.date else False
            return render(request, 'accounts/clientes.html', {'user_token':user_token, 'expirado':expirado})
        return render(request, 'accounts/clientes.html')
    
    # Se o usuário não possuir Token a tela será exibida possibilitará criar chaves.
    except ClientAccountToken.DoesNotExist:
        return render(request, 'accounts/clientes.html')
    

accounts/views/recover_view.py
from django.contrib import messages
from django.shortcuts import redirect, render

from accounts.forms.form_recover import RecoverForm


def recover_view(request):
    recover_pass_data = request.session.get('recover_pass', None)
    
    recover_form = RecoverForm(recover_pass_data)    
    return render(request, 'accounts/recover.html',{'recover_form':recover_form})

def proccess_recovery(request):
    if not request.POST:
        del(request.session['recover_pass'])
        return redirect('accounts:recovery')
    
    POST_DATA = request.POST
    request.session['recover_pass'] = POST_DATA
    form = RecoverForm(POST_DATA)
    
    if form.is_valid():
        form.save(commit=True) #commit=False não salva dados
        del(request.session['recover_pass'])
        messages.success(request, 'Senha alterada com sucesso!')
    
    return redirect('accounts:recovery')    

accounts/templates/accounts/clientes.html
{% extends 'base.html' %}

{% block title %} Persons | Painel do Usuário {% endblock %}

{% block main %}
<div class="flex flex-col bg-gradient-to-b from-gray-100 to-blue-100 h-screen">

    <div class="flex flex-col sm:flex-row py-4 px-2 bg-white justify-between border border-b-2 border-gray-300">
        <div class="flex flex-row justify-between items-center gap-2">
            <i class="fa-solid fa-people-group text-blue-600 text-3xl sm:text-2xl"></i>
            <span class="font-mono">
                Olá, {{ request.user.first_name }}
            </span>
        </div>

        <a href="{% url 'persons:initial' %}" class="text-lg text-center text-blue-600 hover:text-blue-700">
            <i class="fa-solid fa-house-user text-4xl sm:text-3xl"></i>
        </a>
        <a href="{% url 'accounts:logout' %}" class="flex items-center w-16 sm:w-auto py-1 px-2 text-white text-center 
        bg-blue-800 hover:bg-blue-700 rounded-lg text-md sm:text-sm mt-8 sm:m-0">
            Logout
            <i class="hidden sm:block fa-solid fa-door-open text-lg ml-1"></i>
        </a>
    </div>

    <div class="flex border border-2 border-gray-50 m-4 rounded-xl shadow-md 
        flex-col bg-gradient-to-b from-blue-200 to-blue-400">

        <div class="flex flex-wrap mt-4 gap-8 p-10 justify-between">

            <div class="flex flex-col w-full bg-white text-center 
            border border-2 border-slate-400 rounded shadow-md">
                {% if user_token %}

                <span class="flex flex-wrap justify-center gap-1 sm:gap-3 py-1 font-semibold">
                    Seu token de acesso atual
                    <span class="bg-blue-700 px-2 text-white rounded-full">{{ user_token.date }}</span>
                </span>

                <span class="bg-slate-400 font-mono break-words">
                    <span
                        class="flex sm:w-20 sm:rounded-br-lg bg-green-600 text-white font-semibold justify-center px-2 mb-2">ACCESS</span>
                    <span id="key_token">{{ user_token.access_token }}</span>

                    <hr class="border border-slate-200 mt-2">

                    <a class="flex justify-center my-4" onclick="copyToClipboard('key_token')">
                        <div class="align-self-auto">
                            <i class="fa-solid fa-copy bg-slate-300 p-1 rounded shadow-lg 
                            text-xl text-blue-800 hover:text-blue-600 cursor-pointer"></i>
                            <p>Copiar</p>
                        </div>
                    </a>

                    <span id="message_api">Token copiado !</span>

                </span>

                {% else %}

                <span class="py-3 font-semibold bg-orange-500">Você ainda não possui tokens</span>
                <div
                    class="flex flex-col py-2 gap-3 items-center w-full bg-gray-100 border border-2 border-gray-300 text-center rounded shadow-md">
                    <span class="py-1 font-semibold">Criar token de acesso</span>
                    <a href="{% url 'accounts:make_tokens' %}" class="items-center w-32 py-1 px-2 text-white text-center bg-blue-800 
                hover:bg-blue-700 rounded-lg text-md">
                        Gerar token
                        <i class="fa-brands fa-keycdn text-lg ml-1"></i>
                    </a>
                </div>

                {% endif %}
            </div>

            {% include 'parts/messages.html' %}

            {% if expirado %}

            <div
                class="flex flex-col py-2 gap-3 items-center w-full bg-gray-100 border border-2 border-gray-300 text-center rounded shadow-md">
                <span class="py-1 font-semibold">Gerar novo token de acesso</span>
                <a href="{% url 'accounts:make_tokens' %}" class="items-center w-32 py-1 px-2 text-white text-center bg-blue-800 
                hover:bg-blue-700 rounded-lg text-md">
                    Gerar token
                    <i class="fa-brands fa-keycdn text-lg ml-1"></i>
                </a>
            </div>

            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/create.html
{% extends 'base.html' %}

{% block title %} Persons | Create {% endblock %}

{% block main %}
<div class="flex bg-gradient-to-tr from-gray-200 via-gray-100 to-gray-200 h-screen justify-center items-center">

    <div class="w-80 sm:w-screen max-w-md bg-white rounded-lg shadow">

        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <span class="text-xl font-bold leading-tight tracking-tight text-blue-700 md:text-2xl">
                <i class="fa-solid fa-people-group"></i> Crie sua conta</span>

            <form class="space-y-4" action="{% url 'accounts:create_client' %}" method="post">
                {% csrf_token %}
                {% for field in create_user_form %}
                <!-- <label for="{{field.id_for_label}}">{{field.label}}</label> --> <!-- Use label se quiser -->
                <!-- Qualquer coisa relacionada a field é sempre field + alguma coisa como ex: field.help_text que está lá em login_form -->
                {{field}}
                <span class="text-red-400 font-bold text-sm">{{ field.errors }}</span>
                {% endfor %}

                {% include 'parts/messages.html' %}

                <div class="flex flex-wrap">
                    <button type="submit"
                        class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                        Criar usuário <i class="fa-solid fa-user-plus"></i>
                    </button>

                    <a href="{% url 'persons:initial' %}"
                        class="text-lg text-center text-blue-600 hover:text-blue-700 mt-4 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium">
                        <i class="fa-solid fa-circle-arrow-left"></i> Início
                    </a>
                </div>

                <p class="text-sm text-center font-light text-gray-700">Já possui uma conta?
                    <a href="{% url 'accounts:login' %}" class="font-medium text-blue-700 hover:underline">
                        clique aqui <i class="fa-solid fa-lock-open"></i>
                    </a>
                </p>
            </form>
        </div>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/recover.html
{% extends 'base.html' %}

{% block title %} Persons | Recuperação de senha {% endblock %}

{% block main %}
<div class="flex bg-gradient-to-tr from-gray-200 via-gray-100 to-gray-200 h-screen justify-center items-center">

    <div class="w-80 sm:w-screen max-w-md bg-white rounded-lg shadow">

        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <span class="text-xl font-bold leading-tight tracking-tight text-blue-700 md:text-2xl">
                <i class="fa-solid fa-people-group"></i> Recuperação de senha</span>

            <form class="space-y-4" action="{% url 'accounts:change_pass' %}" method="post">
                {% csrf_token %}
                {% for field in recover_form %}
                {{field}}
                <span class="text-red-400 font-bold text-sm">{{ field.errors }}</span>
                {% endfor %}

                {% include 'parts/messages.html' %}

                <div class="flex flex-wrap">
                    <button type="submit"
                        class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                        Alterar Senha <i class="fa-solid fa-paper-plane"></i>
                    </button>

                    <a href="{% url 'accounts:login' %}"
                        class="text-lg text-center text-blue-600 hover:text-blue-700 mt-4 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium">
                        <i class="fa-solid fa-circle-arrow-left"></i> Login
                    </a>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/userlogin.html
{% extends 'base.html' %}

{% block title %} Persons | Login {% endblock %}

{% block main %}
<div class="flex bg-gradient-to-tr from-gray-200 via-gray-100 to-gray-200 h-screen justify-center items-center">

  <div class="w-80 sm:w-screen max-w-md bg-white rounded-lg shadow">

    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
      <span class="text-xl font-bold leading-tight tracking-tight text-blue-700 md:text-2xl">
        <i class="fa-solid fa-people-group"></i> Login de usuário</span>

      <form class="space-y-4" action="{% url 'accounts:verify_login' %}" method="post">

        {% if not request.user.is_authenticated %}

        {% csrf_token %}
        {% for field in user_data_form %}
        <!-- <label for="{{field.id_for_label}}">{{field.label}}</label> --> <!-- Use label se quiser -->
        <!-- Qualquer coisa relacionada a field é sempre field + alguma coisa como ex: field.help_text que está lá em login_form -->
        {{field}}
        <span class="text-red-400 font-bold text-sm">{{ field.errors }}</span>
        {% endfor %}

        <div class="flex items-center justify-end"><a href="{% url 'accounts:recovery' %}"
            class="text-sm font-medium text-red-600 hover:underline">Esqueceu a senha?</a>
        </div>

        {% include 'parts/messages.html' %}

        {% endif %}

        <div class="flex flex-wrap">

          {% if request.user.is_authenticated %}

          <div class="w-full mb-5 font-mono tracking-tighter text-center">
            Você está atualmente logado como:
            <span class="text-white bg-green-600 px-2 rounded">
              {{ request.user.first_name }}
            </span>
          </div>

          <a href="{% url 'accounts:client' %}" class="flex flex-col font-semibold text-blue-400 hover:text-blue-600 bg-blue-600 hover:bg-blue-300 
            w-full mb-10 text-center py-2 cursor-pointer rounded shadow-sm">
            <i class="fa-solid fa-tachograph-digital text-2xl"></i>
            <span>Painel do usuário</span>
          </a>

          <a href="{% url 'accounts:logout' %}" class="w-full text-white bg-blue-800 hover:bg-blue-700 focus:ring-4 
          focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
            Logout <i class="fa-solid fa-person-walking-arrow-right text-lg ml-1"></i>
            <i class="fa-solid fa-door-open text-lg ml-1"></i>
          </a>

          {% else %}

          <button type="submit"
            class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
            Login <i class="fa-solid fa-key"></i>
          </button>

          {% endif %}

          <a href="{% url 'persons:initial' %}"
            class="text-lg text-center text-blue-600 hover:text-blue-700 mt-4 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium">
            <i class="fa-solid fa-circle-arrow-left"></i> Início
          </a>

        </div>
      </form>
    </div>
  </div>

</div>
{% endblock %}